version: "3.9"

services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      # הגדרות KRaft
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # מזהה רנדומלי ל-Cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  api:
    build: ./app/api
    depends_on:
      - kafka
      - mongo
      - redis
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_ORDERS_TOPIC: "orders-pizza"
    ports:
      - "8000:8000"

  worker_kitchen:
    build: ./consumer_worker
    depends_on:
      - kafka
      - mongo
      - redis
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_ORDERS_TOPIC: "orders-pizza"
      KAFKA_GROUP_ID: "kitchen-team"

  worker_text:
    build: ./workers/text_worker
    depends_on:
      - kafka
      - mongo
      - redis
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_ORDERS_TOPIC: "orders-pizza"
      KAFKA_GROUP_ID: "text-team"

volumes:
  mongo_data:
